name: called-workflow-2

on:
    workflow_call:
        inputs:
            invocation:
                description: The invocation number
                default: 0
                required: false
                type: number

jobs:
    Called-2-Job-0:
        runs-on: ubuntu-latest
        steps:
            - run: echo "called-workflow-2 Called-Job-0 Step 0 invocation ${{ inputs.invocation }}"
