name: scm-logs-simple

on: push

jobs:

    Job-0:
        runs-on: ubuntu-latest
        steps:
            - id: step-0
              name: Step 0
              run: |
                echo "Job-0 step 0"
            - run: echo "Job-0 step 1"

    Job-1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job-1 step 0"


    Job-2-Matrix:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                slice: ["a", "b"]
                chunk: [1, 2]
        steps:
            - run: Echo "Job-2-Matrix step 0 slice ${{ matrix.slice }} chunk ${{ matrix.chunk }}"

    Job-3-Call-Workflow:
        uses: ./.github/workflows/called.yaml@main
        with:
            username: mona
